description: Success response for updating room config
content:
    application/json:
        schema:
            type: object
            properties:
                message:
                    type: string
        example:
            message: Room config for room 'room-123' updated successfully
