packages:
  - ../openvidu/openvidu-components-angular/projects/openvidu-components-angular
  - meet-ce/typings
  - meet-ce/frontend
  - meet-ce/frontend/webcomponent
  - meet-ce/frontend/projects/shared-meet-components
  - meet-ce/backend
  - meet-pro/frontend
  - meet-pro/backend
  - meet-pro/typings
  - testapp

ignoredBuiltDependencies:
  - chromedriver
  - core-js
  - esbuild

onlyBuiltDependencies:
  - bcrypt
