description: Successfully updated webhooks config
content:
    application/json:
        schema:
            type: object
            properties:
                message:
                    type: string
                    example: 'Webhooks config updated successfully'
