/** THIS HEADER IS AUTOGENERATED. DO NOT MODIFY MANUALLY. For any changes, please update the '/openvidu-meet/typings' directory. */

import { MeetRecordingInfo } from './recording.model.js';
import { OpenViduMeetRoom } from './room.js';

export type MeetWebhookPayload = MeetRecordingInfo | OpenViduMeetRoom;

export const enum MeetWebhookEventType {
	RECORDING_STARTED = 'recordingStarted',
	RECORDING_UPDATED = 'recordingUpdated',
	RECORDING_ENDED = 'recordingEnded',
	ROOM_FINISHED = 'roomFinished',
}

export interface MeetWebhookEvent {
	creationDate: number;
	event: MeetWebhookEventType;
	data: MeetWebhookPayload;
}
