openapi: 3.1.0
info:
    $ref: './info/info.yaml'
servers:
    - url: meet/api/v1
      description: OpenVidu Meet API
tags:
    $ref: './tags/tags.yaml'
webhooks:
    $ref: './webhooks/webhooks.yaml'
paths:
    /rooms:
        $ref: './paths/rooms.yaml#/~1rooms'
    /rooms/{roomId}:
        $ref: './paths/rooms.yaml#/~1rooms~1{roomId}'
    /rooms/{roomId}/config:
        $ref: './paths/rooms.yaml#/~1rooms~1{roomId}~1config'
    /rooms/{roomId}/roles:
        $ref: './paths/rooms.yaml#/~1rooms~1{roomId}~1roles'
    /rooms/{roomId}/anonymous:
        $ref: './paths/rooms.yaml#/~1rooms~1{roomId}~1anonymous'
    /rooms/{roomId}/status:
        $ref: './paths/rooms.yaml#/~1rooms~1{roomId}~1status'
    /rooms/{roomId}/members:
        $ref: './paths/room-members.yaml#/~1rooms~1{roomId}~1members'
    /rooms/{roomId}/members/{memberId}:
        $ref: './paths/room-members.yaml#/~1rooms~1{roomId}~1members~1{memberId}'
    /recordings:
        $ref: './paths/recordings.yaml#/~1recordings'
    /recordings/download:
        $ref: './paths/recordings.yaml#/~1recordings~1download'
    /recordings/{recordingId}:
        $ref: './paths/recordings.yaml#/~1recordings~1{recordingId}'
    /recordings/{recordingId}/media:
        $ref: './paths/recordings.yaml#/~1recordings~1{recordingId}~1media'
    /recordings/{recordingId}/url:
        $ref: './paths/recordings.yaml#/~1recordings~1{recordingId}~1url'
    /recordings/{recordingId}/stop:
        $ref: './paths/recordings.yaml#/~1recordings~1{recordingId}~1stop'
components:
    securitySchemes:
        $ref: './components/security.yaml'
    schemas:
        MeetRoom:
            $ref: components/schemas/meet-room.yaml
        MeetRoomConfig:
            $ref: './components/schemas/meet-room-config.yaml#/MeetRoomConfig'
        MeetRoomMember:
            $ref: components/schemas/meet-room-member.yaml
        MeetPermissions:
            $ref: components/schemas/meet-permissions.yaml
        MeetRecording:
            $ref: components/schemas/meet-recording.yaml
        MeetWebhookEvent:
            $ref: components/schemas/meet-webhook.yaml#/MeetWebhookEvent
        Error:
            $ref: components/schemas/error.yaml
