openapi: 3.1.0
info:
    $ref: './info/info.yaml'
servers:
    - url: /api/v1
      description: OpenVidu Meet API
tags:
    $ref: './tags/tags.yaml'
webhooks:
    $ref: './webhooks/webhooks.yaml'
paths:
    /rooms:
        $ref: './paths/rooms.yaml#/~1rooms'
    /rooms/{roomId}:
        $ref: './paths/rooms.yaml#/~1rooms~1{roomId}'
    /rooms/{roomId}/config:
        $ref: './paths/rooms.yaml#/~1rooms~1{roomId}~1config'
    /rooms/{roomId}/status:
        $ref: './paths/rooms.yaml#/~1rooms~1{roomId}~1status'
    /recordings:
        $ref: './paths/recordings.yaml#/~1recordings'
    /recordings/download:
        $ref: './paths/recordings.yaml#/~1recordings~1download'
    /recordings/{recordingId}:
        $ref: './paths/recordings.yaml#/~1recordings~1{recordingId}'
    /recordings/{recordingId}/media:
        $ref: './paths/recordings.yaml#/~1recordings~1{recordingId}~1media'
    /recordings/{recordingId}/url:
        $ref: './paths/recordings.yaml#/~1recordings~1{recordingId}~1url'
components:
    securitySchemes:
        $ref: './components/security.yaml'
    schemas:
        MeetRoom:
            $ref: components/schemas/meet-room.yaml
        MeetRoomOptions:
            $ref: components/schemas/meet-room-options.yaml
        MeetRoomConfig:
            $ref: './components/schemas/meet-room-config.yaml#/MeetRoomConfig'
        MeetRecording:
            $ref: components/schemas/meet-recording.yaml
        MeetWebhookEvent:
            $ref: components/schemas/meet-webhook.yaml#/MeetWebhookEvent
        Error:
            $ref: components/schemas/error.yaml
