openapi: 3.1.0
info:
    $ref: './shared/info.yaml'
servers:
    - url: meet/api/v1
      description: OpenVidu Meet API
tags:
    $ref: './shared/tags.yaml'
webhooks:
    $ref: './webhooks/webhooks.yaml'
paths:
    /users:
        $ref: './users/users.yaml#/~1users'
    /users/{userId}:
        $ref: './users/users.yaml#/~1users~1{userId}'
    /users/{userId}/password:
        $ref: './users/users.yaml#/~1users~1{userId}~1password'
    /users/{userId}/role:
        $ref: './users/users.yaml#/~1users~1{userId}~1role'
    /rooms:
        $ref: './rooms/rooms.yaml#/~1rooms'
    /rooms/{roomId}:
        $ref: './rooms/rooms.yaml#/~1rooms~1{roomId}'
    /rooms/{roomId}/config:
        $ref: './rooms/rooms.yaml#/~1rooms~1{roomId}~1config'
    /rooms/{roomId}/roles:
        $ref: './rooms/rooms.yaml#/~1rooms~1{roomId}~1roles'
    /rooms/{roomId}/access:
        $ref: './rooms/rooms.yaml#/~1rooms~1{roomId}~1access'
    /rooms/{roomId}/status:
        $ref: './rooms/rooms.yaml#/~1rooms~1{roomId}~1status'
    /rooms/{roomId}/members:
        $ref: './room-members/room-members.yaml#/~1rooms~1{roomId}~1members'
    /rooms/{roomId}/members/{memberId}:
        $ref: './room-members/room-members.yaml#/~1rooms~1{roomId}~1members~1{memberId}'
    /recordings:
        $ref: './recordings/recordings.yaml#/~1recordings'
    /recordings/download:
        $ref: './recordings/recordings.yaml#/~1recordings~1download'
    /recordings/{recordingId}:
        $ref: './recordings/recordings.yaml#/~1recordings~1{recordingId}'
    /recordings/{recordingId}/media:
        $ref: './recordings/recordings.yaml#/~1recordings~1{recordingId}~1media'
    /recordings/{recordingId}/url:
        $ref: './recordings/recordings.yaml#/~1recordings~1{recordingId}~1url'
    /recordings/{recordingId}/stop:
        $ref: './recordings/recordings.yaml#/~1recordings~1{recordingId}~1stop'
components:
    securitySchemes:
        $ref: './shared/security.yaml'
    schemas:
        MeetUser:
            $ref: ./users/schemas/meet-user.yaml
        MeetRoom:
            $ref: ./rooms/schemas/meet-room.yaml
        MeetRoomConfig:
            $ref: './rooms/schemas/meet-room-config.yaml#/MeetRoomConfig'
        MeetRoomMember:
            $ref: ./room-members/schemas/meet-room-member.yaml
        MeetPermissions:
            $ref: ./rooms/schemas/meet-permissions.yaml
        MeetRecording:
            $ref: ./recordings/schemas/meet-recording.yaml
        MeetWebhookEvent:
            $ref: ./webhooks/schemas/meet-webhook.yaml#/MeetWebhookEvent
        Error:
            $ref: ./shared/schemas/error.yaml
