openapi: 3.1.0
info:
    $ref: './info/info.yaml'
servers:
    - url: /internal-api/v1
      description: OpenVidu Meet Internal API
tags:
    $ref: './tags/tags.yaml'

paths:
    /auth/login:
        $ref: './paths/internal/auth.yaml#/~1auth~1login'
    /auth/logout:
        $ref: './paths/internal/auth.yaml#/~1auth~1logout'
    /auth/refresh:
        $ref: './paths/internal/auth.yaml#/~1auth~1refresh'
    /api-keys:
        $ref: './paths/internal/api-keys.yaml#/~1auth~1api-keys'
    /users:
        $ref: './paths/internal/users.yaml#/~1users'
    /users/me:
        $ref: './paths/internal/users.yaml#/~1users~1me'
    /users/change-password:
        $ref: './paths/internal/users.yaml#/~1users~1change-password'
    /users/{userId}:
        $ref: './paths/internal/users.yaml#/~1users~1{userId}'
    /config/webhooks:
        $ref: './paths/internal/meet-global-config.yaml#/~1config~1webhooks'
    /config/webhooks/test:
        $ref: './paths/internal/meet-global-config.yaml#/~1config~1webhooks~1test'
    /config/security:
        $ref: './paths/internal/meet-global-config.yaml#/~1config~1security'
    /config/rooms/appearance:
        $ref: './paths/internal/meet-global-config.yaml#/~1config~1rooms~1appearance'
    /config/captions:
        $ref: './paths/internal/meet-global-config.yaml#/~1config~1captions'
    /rooms/{roomId}/token:
        $ref: './paths/internal/rooms.yaml#/~1rooms~1{roomId}~1token'
    /meetings/{roomId}:
        $ref: './paths/internal/meetings.yaml#/~1meetings~1{roomId}'
    /meetings/{roomId}/participants/{participantIdentity}:
        $ref: './paths/internal/meetings.yaml#/~1meetings~1{roomId}~1participants~1{participantIdentity}'
    /meetings/{roomId}/participants/{participantIdentity}/role:
        $ref: './paths/internal/meetings.yaml#/~1meetings~1{roomId}~1participants~1{participantIdentity}~1role'
    /analytics:
        $ref: './paths/internal/analytics.yaml#/~1analytics'

components:
    securitySchemes:
        $ref: components/security.yaml
    schemas:
        MeetApiKey:
            $ref: components/schemas/internal/meet-api-key.yaml
        MeetUser:
            $ref: components/schemas/internal/meet-user.yaml
        WebhooksConfig:
            $ref: components/schemas/internal/webhooks-config.yaml
        SecurityConfig:
            $ref: components/schemas/internal/global-security-config.yaml
        RoomsAppearanceConfig:
            $ref: components/schemas/internal/rooms-appearance-config.yaml
        MeetRoom:
            $ref: components/schemas/meet-room.yaml
        MeetAnalytics:
            $ref: components/schemas/internal/meet-analytics.yaml
        Error:
            $ref: components/schemas/error.yaml
