openapi: 3.1.0
info:
    $ref: './info/info.yaml'
servers:
    - url: /meet/internal-api/v1
      description: OpenVidu Meet Internal API
tags:
    $ref: './tags/tags.yaml'

paths:
    /auth/login:
        $ref: './paths/internal/auth.yaml#/~1auth~1login'
    /auth/logout:
        $ref: './paths/internal/auth.yaml#/~1auth~1logout'
    /auth/refresh:
        $ref: './paths/internal/auth.yaml#/~1auth~1refresh'
    /auth/profile:
        $ref: './paths/internal/auth.yaml#/~1auth~1profile'
    /rooms/{roomId}:
        $ref: './paths/internal/rooms.yaml#/~1rooms~1{roomId}'
    /rooms/{roomId}/participant-role:
        $ref: './paths/internal/rooms.yaml#/~1rooms~1{roomId}~1participant-role'
    /recordings:
        $ref: './paths/internal/recordings.yaml#/~1recordings'
    /recordings/{recordingId}/stop:
        $ref: './paths/internal/recordings.yaml#/~1recordings~1{recordingId}~1stop'
    /participants/token:
        $ref: './paths/internal/participants.yaml#/~1participants~1token'
    /participants/token/refresh:
        $ref: './paths/internal/participants.yaml#/~1participants~1token~1refresh'
    /participants/{participantName}:
        $ref: './paths/internal/participants.yaml#/~1participants~1{participantName}'

components:
    securitySchemes:
        $ref: './components/security.yaml'
    schemas:
        User:
            $ref: components/schemas/internal/user.yaml
        MeetRoom:
            $ref: components/schemas/meet-room.yaml
        MeetRoomOptions:
            $ref: components/schemas/meet-room-options.yaml
        MeetRoomPreferences:
            $ref: './components/schemas/meet-room-preferences.yaml#/MeetRoomPreferences'
        MeetRecording:
            $ref: components/schemas/meet-recording.yaml
        Error:
            $ref: components/schemas/error.yaml
