openapi: 3.1.0
info:
    $ref: './info/info.yaml'
servers:
    - url: /internal-api/v1
      description: OpenVidu Meet Internal API
tags:
    $ref: './tags/tags.yaml'

paths:
    /auth/login:
        $ref: './paths/internal/auth.yaml#/~1auth~1login'
    /auth/logout:
        $ref: './paths/internal/auth.yaml#/~1auth~1logout'
    /auth/refresh:
        $ref: './paths/internal/auth.yaml#/~1auth~1refresh'
    /auth/api-keys:
        $ref: './paths/internal/auth.yaml#/~1auth~1api-keys'
    /users/profile:
        $ref: './paths/internal/users.yaml#/~1users~1profile'
    /users/change-password:
        $ref: './paths/internal/users.yaml#/~1users~1change-password'
    /config/webhooks:
        $ref: './paths/internal/meet-global-config.yaml#/~1config~1webhooks'
    /config/webhooks/test:
        $ref: './paths/internal/meet-global-config.yaml#/~1config~1webhooks~1test'
    /config/security:
        $ref: './paths/internal/meet-global-config.yaml#/~1config~1security'
    /config/rooms/appearance:
        $ref: './paths/internal/meet-global-config.yaml#/~1config~1rooms~1appearance'
    /rooms/{roomId}/recording-token:
        $ref: './paths/internal/rooms.yaml#/~1rooms~1{roomId}~1recording-token'
    /rooms/{roomId}/roles:
        $ref: './paths/internal/rooms.yaml#/~1rooms~1{roomId}~1roles'
    /rooms/{roomId}/roles/{secret}:
        $ref: './paths/internal/rooms.yaml#/~1rooms~1{roomId}~1roles~1{secret}'
    /recordings:
        $ref: './paths/internal/recordings.yaml#/~1recordings'
    /recordings/{recordingId}/stop:
        $ref: './paths/internal/recordings.yaml#/~1recordings~1{recordingId}~1stop'
    /participants/token:
        $ref: './paths/internal/participants.yaml#/~1participants~1token'
    /participants/token/refresh:
        $ref: './paths/internal/participants.yaml#/~1participants~1token~1refresh'
    /meetings/{roomId}:
        $ref: './paths/internal/meetings.yaml#/~1meetings~1{roomId}'
    /meetings/{roomId}/participants/{participantIdentity}:
        $ref: './paths/internal/meetings.yaml#/~1meetings~1{roomId}~1participants~1{participantIdentity}'
    /meetings/{roomId}/participants/{participantIdentity}/role:
        $ref: './paths/internal/meetings.yaml#/~1meetings~1{roomId}~1participants~1{participantIdentity}~1role'

components:
    securitySchemes:
        $ref: components/security.yaml
    schemas:
        User:
            $ref: components/schemas/internal/user.yaml
        WebhooksConfig:
            $ref: components/schemas/internal/webhooks-config.yaml
        SecurityConfig:
            $ref: components/schemas/internal/global-security-config.yaml
        MeetRoom:
            $ref: components/schemas/meet-room.yaml
        MeetRoomOptions:
            $ref: components/schemas/meet-room-options.yaml
        MeetRoomConfig:
            $ref: components/schemas/meet-room-config.yaml#/MeetRoomConfig
        MeetRoomRoleAndPermissions:
            $ref: components/schemas/internal/meet-room-role-permissions.yaml
        MeetRecording:
            $ref: components/schemas/meet-recording.yaml
        Error:
            $ref: components/schemas/error.yaml
