description: Successfully updated security config
content:
    application/json:
        schema:
            type: object
            properties:
                message:
                    type: string
                    example: 'Security config updated successfully'
