import { MeetRoomMemberType } from '@openvidu-meet/typings';
import type { SchemaMigrationMap, SchemaTransform } from '../models/migration.model.js';
import { generateSchemaMigrationName } from '../models/migration.model.js';
import type { MeetRoomMemberDocument } from '../models/mongoose-schemas/room-member.schema.js';
import { meetRoomMemberCollectionName } from '../models/mongoose-schemas/room-member.schema.js';

const roomMemberMigrationV1ToV2Name = generateSchemaMigrationName(meetRoomMemberCollectionName, 1, 2);

/**
 * v1 -> v2: introduces the `type` field on room members.
 *
 * Legacy documents do not store the member type explicitly, so it is derived from the memberId:
 * external members have an autogenerated memberId prefixed with 'ext-', while registered members
 * use the linked userId as their memberId.
 */
const roomMemberMigrationV1ToV2Transform: SchemaTransform<MeetRoomMemberDocument> = (roomMember) => {
	roomMember.type = roomMember.memberId.startsWith('ext-')
		? MeetRoomMemberType.EXTERNAL
		: MeetRoomMemberType.REGISTERED;
	return roomMember;
};

/**
 * Schema migrations for MeetRoomMember.
 * Key format: schema_{collection}_v{from}_to_v{to}
 */
export const roomMemberMigrations: SchemaMigrationMap<MeetRoomMemberDocument> = new Map([
	[roomMemberMigrationV1ToV2Name, roomMemberMigrationV1ToV2Transform]
]);
