description: Successfully updated security config. Returns the updated security configuration.
content:
    application/json:
        schema:
            $ref: '../../schemas/global-security-config.yaml'
