name: WebComponent Unit Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:
    name: WebComponent Unit Tests
    runs-on: ov-actions-runner
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22.13'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.3
      - name: Checkout OpenVidu Meet
        uses: actions/checkout@v4

      - name: Install dependencies
        run: ./meet.sh install

      - name: Build typings
        run: ./meet.sh build-typings --skip-install

      - name: Build webcomponent
        run: ./meet.sh build-webcomponent --skip-install --skip-typings

      - name: Run tests
        run: ./meet.sh test-unit-webcomponent --skip-install

      - name: Clean up
        if: always()
        uses: OpenVidu/actions/cleanup@main
