name: WebComponent Unit Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:
    name: WebComponent Unit Tests
    runs-on: ${{ vars.LABEL_WORKER_SELFHOSTED }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '24.13.1'
      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: 10.18.3
      - name: Checkout OpenVidu Meet
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install dependencies
        run: ./meet.sh install

      - name: Build typings
        run: ./meet.sh build-typings --skip-install

      - name: Build webcomponent
        run: ./meet.sh build-webcomponent --skip-install --skip-typings

      - name: Run tests
        run: ./meet.sh test-unit-webcomponent --skip-install

      - name: Clean up
        if: always()
        uses: OpenVidu/actions/cleanup@35d136377813cf9b0b23d12d16d57864ccf3a8c2 # v1.0.2
